#ADD DNS ENTRIES FOR PIHOLE
- name: Clean DNS custom.list
  tags: dns
  shell: 'rm -f /mnt/media/container-program-files/pihole/custom.list \ 
          && touch /mnt/media/container-program-files/pihole/custom.list'
- name: Add && enforce PiHole DNS Entries
  tags: dns
  lineinfile: 
    dest: "/mnt/media/container-program-files/pihole/custom.list"
    line: '{{ item }}'
  with_items:
    - '10.0.0.49 paperless.branconet.lan'
    - '10.0.0.49 portainer.branconet.lan'
    - '10.0.0.49 lucinda.branconet.lan' 
    - '10.0.0.49 santos.branconet.lan' 
    - '10.0.0.49 aplb.branconet.lan'
    - '10.0.0.49 homeassistant.branconet.lan'
    - '10.0.0.49 glances.branconet.lan'
    - '10.0.0.49 nextcloud.branconet.lan'
    - '10.0.0.49 pihole.branconet.lan'
    - '10.0.0.49 homepage.branconet.lan'
- name: Restart DNS service
  tags: dns
  shell: docker restart pihole-web-app-1
  ignore_errors: true