- name: "Set SSH Enviorment to alternate port"
  shell: "ufw allow ssh && \
            ufw allow 2002/tcp"

- name: Creates SSH hidden directory
  file:
      path: "/home/{{deploy_user}}/.ssh"
      state: directory

- name: Copy a "sshd_config" file from repo to the remote machine
  copy:
    src: "./defaults/sshd_config"
    dest: "/etc/ssh/sshd_config"

- name: "Restart SSH Service"
  shell: "systemctl restart sshd"
  
- name: "Remove and dissable GUI in Ubuntu"
  shell: "apt-get purge ubuntu-desktop -y && \
            systemctl set-default multi-user"
  ignore_errors: true
  no_log: true