# WebServer Block

- name: lucinda.branconet.com
  tags:
    - lucinda.branconet.com
  docker_container:
    name: "ws-lucinda.branconet.com"
    image: "nginx"
    pull: yes
    state: started
    restart_policy: unless-stopped
    ports: 
      - "8080:80"
    volumes:
      - '{{homedir}}/container-program-files/ws-lucinda.branconet.com:/usr/share/nginx/html'

- name: santos.branconet.com
  tags:
    - santos.branconet.com
  docker_container:
    name: "ws-santos.branconet.com"
    image: "nginx"
    pull: yes
    state: started
    restart_policy: unless-stopped
    ports: 
      - "8081:80"
    volumes:
      - '{{homedir}}/container-program-files/ws-santos.branconet.com:/usr/share/nginx/html'

- name: aplb.branconet.com
  tags:
    - aplb.branconet.com
  docker_container:
    name: "ws-aplb.branconet.com"
    image: "nginx"
    pull: yes
    state: started
    restart_policy: unless-stopped
    ports: 
      - "8082:80"
    volumes:
      - '{{homedir}}/container-program-files/ws-aplb.branconet.com:/usr/share/nginx/html'

# Provision Websites

- name: Clone lucinda.branconet.com
  tags:
    - lucinda.branconet.com
  ansible.builtin.git:
    repo: https://github.com/jtmb/lucinda-art-gallery.git
    dest: '{{homedir}}/container-program-files/ws-lucinda.branconet.com'
    version: master

- name: Clone santos.branconet.com
  tags:
    - santos.branconet.com
  ansible.builtin.git:
    repo: https://github.com/jtmb/santosweb.git
    dest: '{{homedir}}/container-program-files/ws-santos.branconet.com'
    version: master

- name: Clone aplb.branconet.com
  tags:
    - aplb.branconet.com
  ansible.builtin.git:
    repo: https://github.com/chucky747/aplb.branconet.com.git
    dest: '{{homedir}}/container-program-files/ws-aplb.branconet.com'
    version: master

# Restart Websites

- name: Restart lucinda.branconet.com
  tags:
    - lucinda.branconet.com
  shell: docker restart ws-lucinda.branconet.com

- name: Restart santos.branconet.com
  tags:
    - santos.branconet.com
  shell: docker restart ws-santos.branconet.com

- name: Restart aplb.branconet.com
  tags:
    - aplb.branconet.com
  shell: docker restart ws-aplb.branconet.com