version: '3.2'
services:
  portainer:
    image: portainer/portainer-ce:latest
    # command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
    - /mnt/media/container-program-files/portainer:/data
    - /var/run/docker.sock:/var/run/docker.sock
